# Generated by Django 5.2.18 on 2026-10-10 11:06

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Order')),
                ('slug', models.SlugField(help_text='URL of the page: /legal/<slug>.', unique=True)),
                ('eyebrow', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=200)),
                ('updated', models.CharField(max_length=200, verbose_name='Effective / updated line')),
                ('intro', models.TextField(blank=True, help_text='Opening paragraph(s). Blank line = new paragraph, lines starting with “- ” are bullets.')),
                ('disclaimer', models.TextField(blank=True, help_text='Small print at the end of the page.')),
                ('compliance_note', models.TextField(blank=True, help_text='Shown as a tooltip on the draft badge.', verbose_name='Internal compliance note')),
            ],
            options={
                'verbose_name': 'Legal document',
                'verbose_name_plural': 'Legal documents',
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='historicalhomepage',
            name='diptych_kwe_items',
        ),
        migrations.RemoveField(
            model_name='historicalhomepage',
            name='diptych_kwe_label',
        ),
        migrations.RemoveField(
            model_name='historicalhomepage',
            name='diptych_traditional_items',
        ),
        migrations.RemoveField(
            model_name='historicalhomepage',
            name='diptych_traditional_label',
        ),
        migrations.RemoveField(
            model_name='historicalsolutionspagesettings',
            name='header_body',
        ),
        migrations.RemoveField(
            model_name='historicalsolutionspagesettings',
            name='header_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='diptych_kwe_items',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='diptych_kwe_label',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='diptych_traditional_items',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='diptych_traditional_label',
        ),
        migrations.RemoveField(
            model_name='solutionspagesettings',
            name='header_body',
        ),
        migrations.RemoveField(
            model_name='solutionspagesettings',
            name='header_title',
        ),
        migrations.AddField(
            model_name='historicalhomepage',
            name='comparison_kwe_label',
            field=models.CharField(default='', help_text='e.g. "The KWE model"', max_length=80, verbose_name='Right column label'),
        ),
        migrations.AddField(
            model_name='historicalhomepage',
            name='comparison_title',
            field=models.CharField(default='', max_length=200, verbose_name='Heading'),
        ),
        migrations.AddField(
            model_name='historicalhomepage',
            name='comparison_traditional_label',
            field=models.CharField(default='', help_text='e.g. "Traditional approach"', max_length=80, verbose_name='Left column label'),
        ),
        migrations.AddField(
            model_name='historicalhomepage',
            name='hero_subtitle',
            field=models.TextField(blank=True, help_text='Supporting line under the headline.', verbose_name='Hero subtitle'),
        ),
        migrations.AddField(
            model_name='historicalhomepage',
            name='team_subtitle',
            field=models.TextField(blank=True, verbose_name='Subtitle'),
        ),
        migrations.AddField(
            model_name='historicalhomewhotile',
            name='group',
            field=models.CharField(default='', help_text='Group heading, e.g. "Private equity". Tiles with the same group are shown together.', max_length=80),
        ),
        migrations.AddField(
            model_name='historicalinsightspagesettings',
            name='hero_subtitle',
            field=models.TextField(blank=True, verbose_name='Subtitle'),
        ),
        migrations.AddField(
            model_name='historicallegalpage',
            name='draft_note',
            field=models.CharField(blank=True, help_text='Badge shown at the top of the Privacy Policy and Terms pages while they await counsel review. Leave empty to hide.', max_length=120, verbose_name='Draft note'),
        ),
        migrations.AddField(
            model_name='historicalsolutionspagesettings',
            name='why_body',
            field=models.TextField(default='', verbose_name='Why KWE body'),
        ),
        migrations.AddField(
            model_name='historicalsolutionspagesettings',
            name='why_title',
            field=models.CharField(default='', help_text='Heading of the intro section, e.g. "Why KWE Advisors".', max_length=200, verbose_name='Why KWE title'),
        ),
        migrations.AddField(
            model_name='historicalstorypage',
            name='hero_kicker',
            field=models.CharField(blank=True, help_text='Short line above the title, e.g. "KWE Fundraising Experience".', max_length=120, verbose_name='Kicker'),
        ),
        migrations.AddField(
            model_name='historicalteammember',
            name='credential',
            field=models.CharField(blank=True, help_text='One-line credential under the role, e.g. "Raised +$3bn of capital".', max_length=160),
        ),
        migrations.AddField(
            model_name='historicalteampagesettings',
            name='hero_subtitle',
            field=models.TextField(blank=True, verbose_name='Subtitle'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='comparison_kwe_label',
            field=models.CharField(default='', help_text='e.g. "The KWE model"', max_length=80, verbose_name='Right column label'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='comparison_title',
            field=models.CharField(default='', max_length=200, verbose_name='Heading'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='comparison_traditional_label',
            field=models.CharField(default='', help_text='e.g. "Traditional approach"', max_length=80, verbose_name='Left column label'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.TextField(blank=True, help_text='Supporting line under the headline.', verbose_name='Hero subtitle'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='team_subtitle',
            field=models.TextField(blank=True, verbose_name='Subtitle'),
        ),
        migrations.AddField(
            model_name='homewhotile',
            name='group',
            field=models.CharField(default='', help_text='Group heading, e.g. "Private equity". Tiles with the same group are shown together.', max_length=80),
        ),
        migrations.AddField(
            model_name='insightspagesettings',
            name='hero_subtitle',
            field=models.TextField(blank=True, verbose_name='Subtitle'),
        ),
        migrations.AddField(
            model_name='legalpage',
            name='draft_note',
            field=models.CharField(blank=True, help_text='Badge shown at the top of the Privacy Policy and Terms pages while they await counsel review. Leave empty to hide.', max_length=120, verbose_name='Draft note'),
        ),
        migrations.AddField(
            model_name='solutionspagesettings',
            name='why_body',
            field=models.TextField(default='', verbose_name='Why KWE body'),
        ),
        migrations.AddField(
            model_name='solutionspagesettings',
            name='why_title',
            field=models.CharField(default='', help_text='Heading of the intro section, e.g. "Why KWE Advisors".', max_length=200, verbose_name='Why KWE title'),
        ),
        migrations.AddField(
            model_name='storypage',
            name='hero_kicker',
            field=models.CharField(blank=True, help_text='Short line above the title, e.g. "KWE Fundraising Experience".', max_length=120, verbose_name='Kicker'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='credential',
            field=models.CharField(blank=True, help_text='One-line credential under the role, e.g. "Raised +$3bn of capital".', max_length=160),
        ),
        migrations.AddField(
            model_name='teampagesettings',
            name='hero_subtitle',
            field=models.TextField(blank=True, verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='historicalteammember',
            name='region',
            field=models.CharField(blank=True, help_text='"Region" filter value, e.g. "London".', max_length=60),
        ),
        migrations.AlterField(
            model_name='historicalteammember',
            name='role',
            field=models.CharField(help_text='Job title shown on the card, e.g. "Senior Advisor".', max_length=80),
        ),
        migrations.AlterField(
            model_name='historicalteammember',
            name='span',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Narrow (3/16)'), (4, 'Regular (4/16)'), (5, 'Wide (5/16)'), (6, 'Extra wide (6/16)')], default=4, help_text='Width of the card in the Team grid on desktop.', verbose_name='Card width'),
        ),
        migrations.AlterField(
            model_name='historicalteammember',
            name='team',
            field=models.CharField(blank=True, help_text='"Team" filter value, e.g. "Founding Partners".', max_length=60),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='region',
            field=models.CharField(blank=True, help_text='"Region" filter value, e.g. "London".', max_length=60),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(help_text='Job title shown on the card, e.g. "Senior Advisor".', max_length=80),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='span',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Narrow (3/16)'), (4, 'Regular (4/16)'), (5, 'Wide (5/16)'), (6, 'Extra wide (6/16)')], default=4, help_text='Width of the card in the Team grid on desktop.', verbose_name='Card width'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='team',
            field=models.CharField(blank=True, help_text='"Team" filter value, e.g. "Founding Partners".', max_length=60),
        ),
        migrations.CreateModel(
            name='HistoricalHomeComparisonRow',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Order')),
                ('label', models.CharField(help_text='Row label, e.g. "Coverage".', max_length=80)),
                ('traditional', models.CharField(max_length=200, verbose_name='Traditional approach')),
                ('kwe', models.CharField(max_length=200, verbose_name='KWE model')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='content.homepage')),
            ],
            options={
                'verbose_name': 'historical Comparison row',
                'verbose_name_plural': 'historical Comparison rows',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalLegalDocument',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Order')),
                ('slug', models.SlugField(help_text='URL of the page: /legal/<slug>.')),
                ('eyebrow', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=200)),
                ('updated', models.CharField(max_length=200, verbose_name='Effective / updated line')),
                ('intro', models.TextField(blank=True, help_text='Opening paragraph(s). Blank line = new paragraph, lines starting with “- ” are bullets.')),
                ('disclaimer', models.TextField(blank=True, help_text='Small print at the end of the page.')),
                ('compliance_note', models.TextField(blank=True, help_text='Shown as a tooltip on the draft badge.', verbose_name='Internal compliance note')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Legal document',
                'verbose_name_plural': 'historical Legal documents',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HomeComparisonRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Order')),
                ('label', models.CharField(help_text='Row label, e.g. "Coverage".', max_length=80)),
                ('traditional', models.CharField(max_length=200, verbose_name='Traditional approach')),
                ('kwe', models.CharField(max_length=200, verbose_name='KWE model')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_rows', to='content.homepage')),
            ],
            options={
                'verbose_name': 'Comparison row',
                'verbose_name_plural': 'Comparison rows',
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalLegalDocumentSection',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Order')),
                ('heading', models.CharField(max_length=160)),
                ('body', models.TextField(help_text='Blank line = new paragraph, lines starting with “- ” are bullets.')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='content.legaldocument')),
            ],
            options={
                'verbose_name': 'historical Section',
                'verbose_name_plural': 'historical Sections',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='LegalDocumentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Order')),
                ('heading', models.CharField(max_length=160)),
                ('body', models.TextField(help_text='Blank line = new paragraph, lines starting with “- ” are bullets.')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='content.legaldocument')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
    ]
