# Generated by Django 5.2.18 on 2026-10-10 11:10

import content.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_item1_final_copy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storyanchor',
            name='page',
        ),
        migrations.RemoveField(
            model_name='casestudiespagesettings',
            name='controls_filter',
        ),
        migrations.RemoveField(
            model_name='casestudiespagesettings',
            name='hero_scroll_cue',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='hero_email',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='hero_linkedin',
        ),
        migrations.RemoveField(
            model_name='historicalcasestudiespagesettings',
            name='controls_filter',
        ),
        migrations.RemoveField(
            model_name='historicalcasestudiespagesettings',
            name='hero_scroll_cue',
        ),
        migrations.RemoveField(
            model_name='historicalcontactpage',
            name='hero_email',
        ),
        migrations.RemoveField(
            model_name='historicalcontactpage',
            name='hero_linkedin',
        ),
        migrations.RemoveField(
            model_name='historicalinsightspagesettings',
            name='hero_scroll_cue',
        ),
        migrations.RemoveField(
            model_name='historicalprocesspage',
            name='hero_anchors',
        ),
        migrations.RemoveField(
            model_name='historicalsolutionspagesettings',
            name='scroll_cue',
        ),
        migrations.RemoveField(
            model_name='historicalteampagesettings',
            name='hero_anchor_href',
        ),
        migrations.RemoveField(
            model_name='historicalteampagesettings',
            name='hero_anchor_label',
        ),
        migrations.RemoveField(
            model_name='historicalteampagesettings',
            name='hero_cta_label',
        ),
        migrations.RemoveField(
            model_name='historicalteampagesettings',
            name='hero_cta_to',
        ),
        migrations.RemoveField(
            model_name='insightspagesettings',
            name='hero_scroll_cue',
        ),
        migrations.RemoveField(
            model_name='processpage',
            name='hero_anchors',
        ),
        migrations.RemoveField(
            model_name='solutionspagesettings',
            name='scroll_cue',
        ),
        migrations.RemoveField(
            model_name='teampagesettings',
            name='hero_anchor_href',
        ),
        migrations.RemoveField(
            model_name='teampagesettings',
            name='hero_anchor_label',
        ),
        migrations.RemoveField(
            model_name='teampagesettings',
            name='hero_cta_label',
        ),
        migrations.RemoveField(
            model_name='teampagesettings',
            name='hero_cta_to',
        ),
        migrations.AddField(
            model_name='historicalinsightspagesettings',
            name='article_meta_labels',
            field=content.models.base.LinesField(blank=True, help_text='Labels of the row under the article hero, in order: date, read time, author.', verbose_name='Meta row labels'),
        ),
        migrations.AddField(
            model_name='insightspagesettings',
            name='article_meta_labels',
            field=content.models.base.LinesField(blank=True, help_text='Labels of the row under the article hero, in order: date, read time, author.', verbose_name='Meta row labels'),
        ),
        migrations.AlterField(
            model_name='filtergroup',
            name='key',
            field=models.CharField(blank=True, help_text='Filter dropdowns only: the item field to filter on, e.g. "strategy", "fundType", "region", "team", "focus".', max_length=40),
        ),
        migrations.AlterField(
            model_name='filtergroup',
            name='kind',
            field=models.CharField(choices=[('dropdown', 'Filter dropdown'), ('categories', 'Categories dropdown'), ('readtime', 'Read-time dropdown')], default='dropdown', max_length=20),
        ),
        migrations.AlterField(
            model_name='filteroption',
            name='value',
            field=models.CharField(blank=True, help_text='Unused by the current site; kept for future filter types.', max_length=80),
        ),
        migrations.AlterField(
            model_name='historicalfiltergroup',
            name='key',
            field=models.CharField(blank=True, help_text='Filter dropdowns only: the item field to filter on, e.g. "strategy", "fundType", "region", "team", "focus".', max_length=40),
        ),
        migrations.AlterField(
            model_name='historicalfiltergroup',
            name='kind',
            field=models.CharField(choices=[('dropdown', 'Filter dropdown'), ('categories', 'Categories dropdown'), ('readtime', 'Read-time dropdown')], default='dropdown', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalfilteroption',
            name='value',
            field=models.CharField(blank=True, help_text='Unused by the current site; kept for future filter types.', max_length=80),
        ),
        migrations.AlterField(
            model_name='historicalhomepage',
            name='hero_scroll_cue',
            field=models.CharField(help_text='Small label at the bottom of the hero, e.g. "Scroll to discover". Used by the hero on every page.', max_length=60, verbose_name='Scroll cue'),
        ),
        migrations.AlterField(
            model_name='historicalsitesettings',
            name='hero_video_url',
            field=models.CharField(blank=True, help_text='Full URL or a path shipped with the site, e.g. "/media/hero.mp4" — used only when no file is uploaded.', max_length=500, verbose_name='Hero video URL'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_scroll_cue',
            field=models.CharField(help_text='Small label at the bottom of the hero, e.g. "Scroll to discover". Used by the hero on every page.', max_length=60, verbose_name='Scroll cue'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_video_url',
            field=models.CharField(blank=True, help_text='Full URL or a path shipped with the site, e.g. "/media/hero.mp4" — used only when no file is uploaded.', max_length=500, verbose_name='Hero video URL'),
        ),
        migrations.DeleteModel(
            name='HistoricalStoryAnchor',
        ),
        migrations.DeleteModel(
            name='StoryAnchor',
        ),
    ]
