# Generated by Django 5.2.18 on 2026-10-10 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_item2_uniform_hero'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalprocesspage',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Process page', 'verbose_name_plural': 'historical Process page'},
        ),
        migrations.AlterModelOptions(
            name='historicalstorypage',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Story page', 'verbose_name_plural': 'historical Story page'},
        ),
        migrations.AlterModelOptions(
            name='processpage',
            options={'verbose_name': 'Process page', 'verbose_name_plural': 'Process page'},
        ),
        migrations.AlterModelOptions(
            name='storypage',
            options={'verbose_name': 'Story page', 'verbose_name_plural': 'Story page'},
        ),
    ]
