# Generated by Django 5.2.18 on 2026-10-10 11:17

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_item3_page_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeapproachstep',
            name='page',
        ),
        migrations.RemoveField(
            model_name='historicalhomepage',
            name='approach_eyebrow',
        ),
        migrations.RemoveField(
            model_name='historicalhomepage',
            name='approach_link_label',
        ),
        migrations.RemoveField(
            model_name='historicalhomepage',
            name='approach_link_to',
        ),
        migrations.RemoveField(
            model_name='historicalhomepage',
            name='approach_title',
        ),
        migrations.RemoveField(
            model_name='historicalhomepage',
            name='logos',
        ),
        migrations.RemoveField(
            model_name='historicalstorypage',
            name='vision_index',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='approach_eyebrow',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='approach_link_label',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='approach_link_to',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='approach_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='logos',
        ),
        migrations.RemoveField(
            model_name='storypage',
            name='vision_index',
        ),
        migrations.AlterField(
            model_name='historicalhomechallengeitem',
            name='icon',
            field=models.CharField(choices=[('target', 'Target'), ('people', 'People'), ('doc', 'Document'), ('bank', 'Bank'), ('globe', 'Globe'), ('leaf', 'Leaf'), ('map', 'Map'), ('star', 'Star'), ('layers', 'Layers'), ('check', 'Check'), ('puzzle', 'Puzzle'), ('clock', 'Clock'), ('chat', 'Chat'), ('link', 'Link'), ('chart', 'Chart (asset manager)'), ('shield', 'Shield (insurer / bank)')], default='target', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalprocesswhycard',
            name='icon',
            field=models.CharField(choices=[('target', 'Target'), ('people', 'People'), ('doc', 'Document'), ('bank', 'Bank'), ('globe', 'Globe'), ('leaf', 'Leaf'), ('map', 'Map'), ('star', 'Star'), ('layers', 'Layers'), ('check', 'Check'), ('puzzle', 'Puzzle'), ('clock', 'Clock'), ('chat', 'Chat'), ('link', 'Link'), ('chart', 'Chart (asset manager)'), ('shield', 'Shield (insurer / bank)')], default='target', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalsolutiondeliverable',
            name='icon',
            field=models.CharField(choices=[('target', 'Target'), ('people', 'People'), ('doc', 'Document'), ('bank', 'Bank'), ('globe', 'Globe'), ('leaf', 'Leaf'), ('map', 'Map'), ('star', 'Star'), ('layers', 'Layers'), ('check', 'Check'), ('puzzle', 'Puzzle'), ('clock', 'Clock'), ('chat', 'Chat'), ('link', 'Link'), ('chart', 'Chart (asset manager)'), ('shield', 'Shield (insurer / bank)')], default='check', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalsolutionexpectation',
            name='icon',
            field=models.CharField(choices=[('target', 'Target'), ('people', 'People'), ('doc', 'Document'), ('bank', 'Bank'), ('globe', 'Globe'), ('leaf', 'Leaf'), ('map', 'Map'), ('star', 'Star'), ('layers', 'Layers'), ('check', 'Check'), ('puzzle', 'Puzzle'), ('clock', 'Clock'), ('chat', 'Chat'), ('link', 'Link'), ('chart', 'Chart (asset manager)'), ('shield', 'Shield (insurer / bank)')], default='check', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalstorypage',
            name='vision_highlight',
            field=models.CharField(help_text='Rendered in the accent colour.', max_length=200, verbose_name='Highlighted text'),
        ),
        migrations.AlterField(
            model_name='homechallengeitem',
            name='icon',
            field=models.CharField(choices=[('target', 'Target'), ('people', 'People'), ('doc', 'Document'), ('bank', 'Bank'), ('globe', 'Globe'), ('leaf', 'Leaf'), ('map', 'Map'), ('star', 'Star'), ('layers', 'Layers'), ('check', 'Check'), ('puzzle', 'Puzzle'), ('clock', 'Clock'), ('chat', 'Chat'), ('link', 'Link'), ('chart', 'Chart (asset manager)'), ('shield', 'Shield (insurer / bank)')], default='target', max_length=20),
        ),
        migrations.AlterField(
            model_name='processwhycard',
            name='icon',
            field=models.CharField(choices=[('target', 'Target'), ('people', 'People'), ('doc', 'Document'), ('bank', 'Bank'), ('globe', 'Globe'), ('leaf', 'Leaf'), ('map', 'Map'), ('star', 'Star'), ('layers', 'Layers'), ('check', 'Check'), ('puzzle', 'Puzzle'), ('clock', 'Clock'), ('chat', 'Chat'), ('link', 'Link'), ('chart', 'Chart (asset manager)'), ('shield', 'Shield (insurer / bank)')], default='target', max_length=20),
        ),
        migrations.AlterField(
            model_name='solutiondeliverable',
            name='icon',
            field=models.CharField(choices=[('target', 'Target'), ('people', 'People'), ('doc', 'Document'), ('bank', 'Bank'), ('globe', 'Globe'), ('leaf', 'Leaf'), ('map', 'Map'), ('star', 'Star'), ('layers', 'Layers'), ('check', 'Check'), ('puzzle', 'Puzzle'), ('clock', 'Clock'), ('chat', 'Chat'), ('link', 'Link'), ('chart', 'Chart (asset manager)'), ('shield', 'Shield (insurer / bank)')], default='check', max_length=20),
        ),
        migrations.AlterField(
            model_name='solutionexpectation',
            name='icon',
            field=models.CharField(choices=[('target', 'Target'), ('people', 'People'), ('doc', 'Document'), ('bank', 'Bank'), ('globe', 'Globe'), ('leaf', 'Leaf'), ('map', 'Map'), ('star', 'Star'), ('layers', 'Layers'), ('check', 'Check'), ('puzzle', 'Puzzle'), ('clock', 'Clock'), ('chat', 'Chat'), ('link', 'Link'), ('chart', 'Chart (asset manager)'), ('shield', 'Shield (insurer / bank)')], default='check', max_length=20),
        ),
        migrations.AlterField(
            model_name='storypage',
            name='vision_highlight',
            field=models.CharField(help_text='Rendered in the accent colour.', max_length=200, verbose_name='Highlighted text'),
        ),
        migrations.CreateModel(
            name='HistoricalHomeTrustedLogo',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Order')),
                ('name', models.CharField(max_length=80)),
                ('icon', models.CharField(choices=[('target', 'Target'), ('people', 'People'), ('doc', 'Document'), ('bank', 'Bank'), ('globe', 'Globe'), ('leaf', 'Leaf'), ('map', 'Map'), ('star', 'Star'), ('layers', 'Layers'), ('check', 'Check'), ('puzzle', 'Puzzle'), ('clock', 'Clock'), ('chat', 'Chat'), ('link', 'Link'), ('chart', 'Chart (asset manager)'), ('shield', 'Shield (insurer / bank)')], default='bank', help_text='Generic firm-type glyph shown next to the name.', max_length=20)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='content.homepage')),
            ],
            options={
                'verbose_name': 'historical Trusted-by logo',
                'verbose_name_plural': 'historical Trusted-by logos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HomeTrustedLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Order')),
                ('name', models.CharField(max_length=80)),
                ('icon', models.CharField(choices=[('target', 'Target'), ('people', 'People'), ('doc', 'Document'), ('bank', 'Bank'), ('globe', 'Globe'), ('leaf', 'Leaf'), ('map', 'Map'), ('star', 'Star'), ('layers', 'Layers'), ('check', 'Check'), ('puzzle', 'Puzzle'), ('clock', 'Clock'), ('chat', 'Chat'), ('link', 'Link'), ('chart', 'Chart (asset manager)'), ('shield', 'Shield (insurer / bank)')], default='bank', help_text='Generic firm-type glyph shown next to the name.', max_length=20)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_logos', to='content.homepage')),
            ],
            options={
                'verbose_name': 'Trusted-by logo',
                'verbose_name_plural': 'Trusted-by logos',
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='HistoricalHomeApproachStep',
        ),
        migrations.DeleteModel(
            name='HomeApproachStep',
        ),
    ]
