# Generated by Django 5.2.18 on 2026-10-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_item4_home_changes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalhomestat',
            name='tone',
            field=models.CharField(choices=[('g1', 'G1 — dark green (#061B20)'), ('g2', 'G2 (#2D4748)'), ('g3', 'G3 (#4C6569)'), ('g4', 'G4 (#729597)'), ('g5', 'G5 (#9CB5B9)'), ('g6', 'G6 — light (#C5D4D7)'), ('sage', 'Sage (#DCE5E6)'), ('off', 'Off-white (#FAFAFA)'), ('white', 'White')], default='g1', help_text='Tile background colour.', max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalhometestimonial',
            name='tone',
            field=models.CharField(choices=[('g1', 'G1 — dark green (#061B20)'), ('g2', 'G2 (#2D4748)'), ('g3', 'G3 (#4C6569)'), ('g4', 'G4 (#729597)'), ('g5', 'G5 (#9CB5B9)'), ('g6', 'G6 — light (#C5D4D7)'), ('sage', 'Sage (#DCE5E6)'), ('off', 'Off-white (#FAFAFA)'), ('white', 'White')], default='g1', help_text='Card gradient.', max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalhomewhotile',
            name='tone',
            field=models.CharField(choices=[('g1', 'G1 — dark green (#061B20)'), ('g2', 'G2 (#2D4748)'), ('g3', 'G3 (#4C6569)'), ('g4', 'G4 (#729597)'), ('g5', 'G5 (#9CB5B9)'), ('g6', 'G6 — light (#C5D4D7)'), ('sage', 'Sage (#DCE5E6)'), ('off', 'Off-white (#FAFAFA)'), ('white', 'White')], default='g1', max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalprocesswhycard',
            name='tone',
            field=models.CharField(choices=[('g1', 'G1 — dark green (#061B20)'), ('g2', 'G2 (#2D4748)'), ('g3', 'G3 (#4C6569)'), ('g4', 'G4 (#729597)'), ('g5', 'G5 (#9CB5B9)'), ('g6', 'G6 — light (#C5D4D7)'), ('sage', 'Sage (#DCE5E6)'), ('off', 'Off-white (#FAFAFA)'), ('white', 'White')], default='sage', help_text='Card background colour.', max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalstorymilestone',
            name='current',
            field=models.BooleanField(default=False, help_text='Tick for the latest milestone (highlighted in white).'),
        ),
        migrations.AlterField(
            model_name='historicalstorypillar',
            name='accent',
            field=models.BooleanField(default=False, help_text='Tick to draw the hairline in white (accent).'),
        ),
        migrations.AlterField(
            model_name='homestat',
            name='tone',
            field=models.CharField(choices=[('g1', 'G1 — dark green (#061B20)'), ('g2', 'G2 (#2D4748)'), ('g3', 'G3 (#4C6569)'), ('g4', 'G4 (#729597)'), ('g5', 'G5 (#9CB5B9)'), ('g6', 'G6 — light (#C5D4D7)'), ('sage', 'Sage (#DCE5E6)'), ('off', 'Off-white (#FAFAFA)'), ('white', 'White')], default='g1', help_text='Tile background colour.', max_length=10),
        ),
        migrations.AlterField(
            model_name='hometestimonial',
            name='tone',
            field=models.CharField(choices=[('g1', 'G1 — dark green (#061B20)'), ('g2', 'G2 (#2D4748)'), ('g3', 'G3 (#4C6569)'), ('g4', 'G4 (#729597)'), ('g5', 'G5 (#9CB5B9)'), ('g6', 'G6 — light (#C5D4D7)'), ('sage', 'Sage (#DCE5E6)'), ('off', 'Off-white (#FAFAFA)'), ('white', 'White')], default='g1', help_text='Card gradient.', max_length=10),
        ),
        migrations.AlterField(
            model_name='homewhotile',
            name='tone',
            field=models.CharField(choices=[('g1', 'G1 — dark green (#061B20)'), ('g2', 'G2 (#2D4748)'), ('g3', 'G3 (#4C6569)'), ('g4', 'G4 (#729597)'), ('g5', 'G5 (#9CB5B9)'), ('g6', 'G6 — light (#C5D4D7)'), ('sage', 'Sage (#DCE5E6)'), ('off', 'Off-white (#FAFAFA)'), ('white', 'White')], default='g1', max_length=10),
        ),
        migrations.AlterField(
            model_name='processwhycard',
            name='tone',
            field=models.CharField(choices=[('g1', 'G1 — dark green (#061B20)'), ('g2', 'G2 (#2D4748)'), ('g3', 'G3 (#4C6569)'), ('g4', 'G4 (#729597)'), ('g5', 'G5 (#9CB5B9)'), ('g6', 'G6 — light (#C5D4D7)'), ('sage', 'Sage (#DCE5E6)'), ('off', 'Off-white (#FAFAFA)'), ('white', 'White')], default='sage', help_text='Card background colour.', max_length=10),
        ),
        migrations.AlterField(
            model_name='storymilestone',
            name='current',
            field=models.BooleanField(default=False, help_text='Tick for the latest milestone (highlighted in white).'),
        ),
        migrations.AlterField(
            model_name='storypillar',
            name='accent',
            field=models.BooleanField(default=False, help_text='Tick to draw the hairline in white (accent).'),
        ),
    ]
