# Generated by Django 5.2.18 on 2026-10-10 11:29

import content.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_item5_no_berry_tones'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalhomepage',
            name='comparison_kwe_image',
            field=models.TextField(blank=True, help_text='Background photo of the right column. Upload (max 10 MB: jpg, png, webp, gif, svg, avif). Leave empty to use the external URL below.', max_length=100, validators=[content.validators.validate_image_size, django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif', 'svg', 'avif'])]),
        ),
        migrations.AddField(
            model_name='historicalhomepage',
            name='comparison_kwe_image_url',
            field=models.URLField(blank=True, help_text='External image URL — used only when no file is uploaded.', max_length=500),
        ),
        migrations.AddField(
            model_name='historicalhomepage',
            name='comparison_traditional_image',
            field=models.TextField(blank=True, help_text='Background photo of the left column. Upload (max 10 MB: jpg, png, webp, gif, svg, avif). Leave empty to use the external URL below.', max_length=100, validators=[content.validators.validate_image_size, django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif', 'svg', 'avif'])]),
        ),
        migrations.AddField(
            model_name='historicalhomepage',
            name='comparison_traditional_image_url',
            field=models.URLField(blank=True, help_text='External image URL — used only when no file is uploaded.', max_length=500),
        ),
        migrations.AddField(
            model_name='historicalhomestat',
            name='image',
            field=models.TextField(blank=True, help_text='Upload (max 10 MB: jpg, png, webp, gif, svg, avif). Leave empty to use the external URL below.', max_length=100, validators=[content.validators.validate_image_size, django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif', 'svg', 'avif'])]),
        ),
        migrations.AddField(
            model_name='historicalhomestat',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL — used only when no file is uploaded.', max_length=500),
        ),
        migrations.AddField(
            model_name='historicalhometestimonial',
            name='image',
            field=models.TextField(blank=True, help_text='Upload (max 10 MB: jpg, png, webp, gif, svg, avif). Leave empty to use the external URL below.', max_length=100, validators=[content.validators.validate_image_size, django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif', 'svg', 'avif'])]),
        ),
        migrations.AddField(
            model_name='historicalhometestimonial',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL — used only when no file is uploaded.', max_length=500),
        ),
        migrations.AddField(
            model_name='historicalhomewhatcard',
            name='image',
            field=models.TextField(blank=True, help_text='Upload (max 10 MB: jpg, png, webp, gif, svg, avif). Leave empty to use the external URL below.', max_length=100, validators=[content.validators.validate_image_size, django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif', 'svg', 'avif'])]),
        ),
        migrations.AddField(
            model_name='historicalhomewhatcard',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL — used only when no file is uploaded.', max_length=500),
        ),
        migrations.AddField(
            model_name='historicalhomewhotile',
            name='image',
            field=models.TextField(blank=True, help_text='Upload (max 10 MB: jpg, png, webp, gif, svg, avif). Leave empty to use the external URL below.', max_length=100, validators=[content.validators.validate_image_size, django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif', 'svg', 'avif'])]),
        ),
        migrations.AddField(
            model_name='historicalhomewhotile',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL — used only when no file is uploaded.', max_length=500),
        ),
        migrations.AddField(
            model_name='homepage',
            name='comparison_kwe_image',
            field=models.ImageField(blank=True, help_text='Background photo of the right column. Upload (max 10 MB: jpg, png, webp, gif, svg, avif). Leave empty to use the external URL below.', upload_to='uploads/%Y/%m/', validators=[content.validators.validate_image_size, django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif', 'svg', 'avif'])]),
        ),
        migrations.AddField(
            model_name='homepage',
            name='comparison_kwe_image_url',
            field=models.URLField(blank=True, help_text='External image URL — used only when no file is uploaded.', max_length=500),
        ),
        migrations.AddField(
            model_name='homepage',
            name='comparison_traditional_image',
            field=models.ImageField(blank=True, help_text='Background photo of the left column. Upload (max 10 MB: jpg, png, webp, gif, svg, avif). Leave empty to use the external URL below.', upload_to='uploads/%Y/%m/', validators=[content.validators.validate_image_size, django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif', 'svg', 'avif'])]),
        ),
        migrations.AddField(
            model_name='homepage',
            name='comparison_traditional_image_url',
            field=models.URLField(blank=True, help_text='External image URL — used only when no file is uploaded.', max_length=500),
        ),
        migrations.AddField(
            model_name='homestat',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload (max 10 MB: jpg, png, webp, gif, svg, avif). Leave empty to use the external URL below.', upload_to='uploads/%Y/%m/', validators=[content.validators.validate_image_size, django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif', 'svg', 'avif'])]),
        ),
        migrations.AddField(
            model_name='homestat',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL — used only when no file is uploaded.', max_length=500),
        ),
        migrations.AddField(
            model_name='hometestimonial',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload (max 10 MB: jpg, png, webp, gif, svg, avif). Leave empty to use the external URL below.', upload_to='uploads/%Y/%m/', validators=[content.validators.validate_image_size, django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif', 'svg', 'avif'])]),
        ),
        migrations.AddField(
            model_name='hometestimonial',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL — used only when no file is uploaded.', max_length=500),
        ),
        migrations.AddField(
            model_name='homewhatcard',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload (max 10 MB: jpg, png, webp, gif, svg, avif). Leave empty to use the external URL below.', upload_to='uploads/%Y/%m/', validators=[content.validators.validate_image_size, django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif', 'svg', 'avif'])]),
        ),
        migrations.AddField(
            model_name='homewhatcard',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL — used only when no file is uploaded.', max_length=500),
        ),
        migrations.AddField(
            model_name='homewhotile',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload (max 10 MB: jpg, png, webp, gif, svg, avif). Leave empty to use the external URL below.', upload_to='uploads/%Y/%m/', validators=[content.validators.validate_image_size, django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif', 'svg', 'avif'])]),
        ),
        migrations.AddField(
            model_name='homewhotile',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL — used only when no file is uploaded.', max_length=500),
        ),
    ]
