# Generated by Django 5.2.18 on 2026-10-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_item6_imagery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsitesettings',
            name='footer_disclosure',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_disclosure',
        ),
        migrations.AddField(
            model_name='historicalsitesettings',
            name='footer_email',
            field=models.EmailField(default='', help_text="Shown in the footer's bottom row.", max_length=254, verbose_name='Footer email'),
        ),
        migrations.AddField(
            model_name='historicalsitesettings',
            name='footer_linkedin_label',
            field=models.CharField(default='LinkedIn', help_text="Link text in the footer's bottom row (links to the LinkedIn URL above).", max_length=40, verbose_name='Footer LinkedIn label'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_email',
            field=models.EmailField(default='', help_text="Shown in the footer's bottom row.", max_length=254, verbose_name='Footer email'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_linkedin_label',
            field=models.CharField(default='LinkedIn', help_text="Link text in the footer's bottom row (links to the LinkedIn URL above).", max_length=40, verbose_name='Footer LinkedIn label'),
        ),
    ]
