# Generated by Django 5.2.18 on 2026-10-10 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_item7_footer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perspective',
            name='page',
        ),
        migrations.RemoveField(
            model_name='casestudiespagesettings',
            name='perspectives_compliance',
        ),
        migrations.RemoveField(
            model_name='casestudiespagesettings',
            name='perspectives_eyebrow',
        ),
        migrations.RemoveField(
            model_name='casestudiespagesettings',
            name='perspectives_note',
        ),
        migrations.RemoveField(
            model_name='casestudiespagesettings',
            name='perspectives_title',
        ),
        migrations.RemoveField(
            model_name='casestudiespagesettings',
            name='trusted_eyebrow',
        ),
        migrations.RemoveField(
            model_name='casestudiespagesettings',
            name='trusted_logos',
        ),
        migrations.RemoveField(
            model_name='casestudiespagesettings',
            name='trusted_note',
        ),
        migrations.RemoveField(
            model_name='historicalcasestudiespagesettings',
            name='perspectives_compliance',
        ),
        migrations.RemoveField(
            model_name='historicalcasestudiespagesettings',
            name='perspectives_eyebrow',
        ),
        migrations.RemoveField(
            model_name='historicalcasestudiespagesettings',
            name='perspectives_note',
        ),
        migrations.RemoveField(
            model_name='historicalcasestudiespagesettings',
            name='perspectives_title',
        ),
        migrations.RemoveField(
            model_name='historicalcasestudiespagesettings',
            name='trusted_eyebrow',
        ),
        migrations.RemoveField(
            model_name='historicalcasestudiespagesettings',
            name='trusted_logos',
        ),
        migrations.RemoveField(
            model_name='historicalcasestudiespagesettings',
            name='trusted_note',
        ),
        migrations.DeleteModel(
            name='HistoricalPerspective',
        ),
        migrations.DeleteModel(
            name='Perspective',
        ),
    ]
