# Generated by Django 5.2.18 on 2026-10-10 11:40

import content.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_item9_drop_case_perspectives'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcasestudyresult',
            name='case_study',
        ),
        migrations.RemoveField(
            model_name='historicalcasestudyresult',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalinsightstat',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalinsightstat',
            name='insight',
        ),
        migrations.RemoveField(
            model_name='insightstat',
            name='insight',
        ),
        migrations.RemoveField(
            model_name='casestudy',
            name='key',
        ),
        migrations.RemoveField(
            model_name='casestudy',
            name='outcome',
        ),
        migrations.RemoveField(
            model_name='casestudy',
            name='quote_attribution',
        ),
        migrations.RemoveField(
            model_name='casestudy',
            name='quote_text',
        ),
        migrations.RemoveField(
            model_name='casestudy',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='extracard',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='historicalcasestudy',
            name='key',
        ),
        migrations.RemoveField(
            model_name='historicalcasestudy',
            name='outcome',
        ),
        migrations.RemoveField(
            model_name='historicalcasestudy',
            name='quote_attribution',
        ),
        migrations.RemoveField(
            model_name='historicalcasestudy',
            name='quote_text',
        ),
        migrations.RemoveField(
            model_name='historicalcasestudy',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='historicalextracard',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='historicalinsight',
            name='h2',
        ),
        migrations.RemoveField(
            model_name='historicalinsight',
            name='p1',
        ),
        migrations.RemoveField(
            model_name='historicalinsight',
            name='p2',
        ),
        migrations.RemoveField(
            model_name='historicalinsight',
            name='p3',
        ),
        migrations.RemoveField(
            model_name='historicalinsight',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='historicalinsight',
            name='toc',
        ),
        migrations.RemoveField(
            model_name='historicalinsightspagesettings',
            name='article_toc',
        ),
        migrations.RemoveField(
            model_name='insight',
            name='h2',
        ),
        migrations.RemoveField(
            model_name='insight',
            name='p1',
        ),
        migrations.RemoveField(
            model_name='insight',
            name='p2',
        ),
        migrations.RemoveField(
            model_name='insight',
            name='p3',
        ),
        migrations.RemoveField(
            model_name='insight',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='insight',
            name='toc',
        ),
        migrations.RemoveField(
            model_name='insightspagesettings',
            name='article_toc',
        ),
        migrations.AddField(
            model_name='casestudy',
            name='approach_heading',
            field=models.CharField(default='', max_length=200, verbose_name='Approach heading'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='challenge_heading',
            field=models.CharField(default='', max_length=200, verbose_name='Challenge heading'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='results',
            field=models.TextField(default='', help_text='Blank line = new paragraph, lines starting with “- ” are bullets, **text** is bold.', verbose_name='Results body'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='results_heading',
            field=models.CharField(default='', max_length=200, verbose_name='Results heading'),
        ),
        migrations.AddField(
            model_name='historicalcasestudy',
            name='approach_heading',
            field=models.CharField(default='', max_length=200, verbose_name='Approach heading'),
        ),
        migrations.AddField(
            model_name='historicalcasestudy',
            name='challenge_heading',
            field=models.CharField(default='', max_length=200, verbose_name='Challenge heading'),
        ),
        migrations.AddField(
            model_name='historicalcasestudy',
            name='results',
            field=models.TextField(default='', help_text='Blank line = new paragraph, lines starting with “- ” are bullets, **text** is bold.', verbose_name='Results body'),
        ),
        migrations.AddField(
            model_name='historicalcasestudy',
            name='results_heading',
            field=models.CharField(default='', max_length=200, verbose_name='Results heading'),
        ),
        migrations.AddField(
            model_name='historicalinsight',
            name='body',
            field=models.TextField(default='', help_text='Article text. Lines starting with “## ” / “### ” are section headings (they build the outline in the sidebar). Blank line = new paragraph, lines starting with “- ” are bullets, **text** is bold.'),
        ),
        migrations.AddField(
            model_name='insight',
            name='body',
            field=models.TextField(default='', help_text='Article text. Lines starting with “## ” / “### ” are section headings (they build the outline in the sidebar). Blank line = new paragraph, lines starting with “- ” are bullets, **text** is bold.'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='category',
            field=models.CharField(help_text='Service line shown as the tag in the detail hero and on the Home slider, e.g. "Fundraising Engagement & Execution".', max_length=80),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='challenge',
            field=models.TextField(help_text='Blank line = new paragraph, lines starting with “- ” are bullets, **text** is bold.', verbose_name='Challenge body'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='meta',
            field=content.models.base.LinesField(blank=True, help_text='Values matching the meta labels on the Case studies page settings (Service, Client, Duration). Leave a line empty to hide it.', verbose_name='Meta values'),
        ),
        migrations.AlterField(
            model_name='casestudyapproachstep',
            name='body',
            field=models.TextField(help_text='Blank line = new paragraph, lines starting with “- ” are bullets, **text** is bold.'),
        ),
        migrations.AlterField(
            model_name='historicalcasestudy',
            name='category',
            field=models.CharField(help_text='Service line shown as the tag in the detail hero and on the Home slider, e.g. "Fundraising Engagement & Execution".', max_length=80),
        ),
        migrations.AlterField(
            model_name='historicalcasestudy',
            name='challenge',
            field=models.TextField(help_text='Blank line = new paragraph, lines starting with “- ” are bullets, **text** is bold.', verbose_name='Challenge body'),
        ),
        migrations.AlterField(
            model_name='historicalcasestudy',
            name='meta',
            field=content.models.base.LinesField(blank=True, help_text='Values matching the meta labels on the Case studies page settings (Service, Client, Duration). Leave a line empty to hide it.', verbose_name='Meta values'),
        ),
        migrations.AlterField(
            model_name='historicalcasestudyapproachstep',
            name='body',
            field=models.TextField(help_text='Blank line = new paragraph, lines starting with “- ” are bullets, **text** is bold.'),
        ),
        migrations.AlterField(
            model_name='historicalinsight',
            name='date',
            field=models.CharField(blank=True, help_text='Display date, e.g. "18 Sep 2025". Leave empty to hide.', max_length=40),
        ),
        migrations.AlterField(
            model_name='insight',
            name='date',
            field=models.CharField(blank=True, help_text='Display date, e.g. "18 Sep 2025". Leave empty to hide.', max_length=40),
        ),
        migrations.DeleteModel(
            name='CaseStudyResult',
        ),
        migrations.DeleteModel(
            name='HistoricalCaseStudyResult',
        ),
        migrations.DeleteModel(
            name='HistoricalInsightStat',
        ),
        migrations.DeleteModel(
            name='InsightStat',
        ),
    ]
