# Generated by Django 5.2.18 on 2026-10-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_item10_framer_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinsightspagesettings',
            name='article_outline',
            field=models.CharField(default='Contents', help_text="Heading of the article outline (built automatically from the article's ## / ### headings).", max_length=40, verbose_name='Outline label'),
        ),
        migrations.AddField(
            model_name='insightspagesettings',
            name='article_outline',
            field=models.CharField(default='Contents', help_text="Heading of the article outline (built automatically from the article's ## / ### headings).", max_length=40, verbose_name='Outline label'),
        ),
    ]
