# Generated by Django 5.2.18 on 2026-10-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_item11_article_outline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstorypage',
            name='respond_lead',
            field=models.TextField(help_text='Paragraph under the heading.', verbose_name='Lead'),
        ),
        migrations.AlterField(
            model_name='storypage',
            name='respond_lead',
            field=models.TextField(help_text='Paragraph under the heading.', verbose_name='Lead'),
        ),
    ]
