# Generated by Django 5.2.18 on 2026-10-10 12:24

import content.models.base
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_story_respond_lead_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtraCard',
        ),
        migrations.AlterField(
            model_name='casestudiespagesettings',
            name='detail_meta_labels',
            field=content.models.base.LinesField(blank=True, help_text="Labels of the meta row (Service, Client, Duration), matched by position with each case study's meta values.", verbose_name='Meta labels'),
        ),
        migrations.AlterField(
            model_name='historicalcasestudiespagesettings',
            name='detail_meta_labels',
            field=content.models.base.LinesField(blank=True, help_text="Labels of the meta row (Service, Client, Duration), matched by position with each case study's meta values.", verbose_name='Meta labels'),
        ),
        migrations.DeleteModel(
            name='HistoricalExtraCard',
        ),
    ]
