# Generated by Django 5.2.18 on 2026-10-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_drop_extra_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinsightspagesettings',
            name='article_glossary',
            field=models.CharField(default='Glossary A–Z', help_text="Outline entry that stands for an article's single-letter (A–Z) headings.", max_length=40, verbose_name='Glossary outline label'),
        ),
        migrations.AddField(
            model_name='historicalsitesettings',
            name='show_testimonials',
            field=models.BooleanField(default=True, help_text='Untick to hide the Home testimonials and the Trusted-by names while client approval is pending.', verbose_name='Show testimonials & Trusted by'),
        ),
        migrations.AddField(
            model_name='insightspagesettings',
            name='article_glossary',
            field=models.CharField(default='Glossary A–Z', help_text="Outline entry that stands for an article's single-letter (A–Z) headings.", max_length=40, verbose_name='Glossary outline label'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_testimonials',
            field=models.BooleanField(default=True, help_text='Untick to hide the Home testimonials and the Trusted-by names while client approval is pending.', verbose_name='Show testimonials & Trusted by'),
        ),
    ]
